<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>RestAssured_Maven</artifactId>
    <version>1.0-SNAPSHOT</version>

    <!-- ========================= -->
    <!-- Properties -->
    <!-- ========================= -->

    <properties>

        <!-- Java -->
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Dependency Versions -->
        <cucumber.version>7.15.0</cucumber.version>
        <junit.version>4.13.2</junit.version>
        <restassured.version>5.4.0</restassured.version>
        <allure.adapter.version>2.32.0</allure.adapter.version>
        <allure.plugin.version>2.17.0</allure.plugin.version>

    </properties>

    <!-- ========================= -->
    <!-- Dependencies -->
    <!-- ========================= -->

    <dependencies>

        <!-- Cucumber -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- JUnit -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Rest Assured -->
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${restassured.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-path</artifactId>
            <version>${restassured.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Jackson -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.15.2</version>
            <scope>test</scope>
        </dependency>

        <!-- Allure -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-cucumber7-jvm</artifactId>
            <version>${allure.adapter.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <!-- ========================= -->
    <!-- Build -->
    <!-- ========================= -->

    <build>

        <plugins>

            <!-- Generate Current IST Time -->
            <plugin>

                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.5.0</version>

                <executions>

                    <execution>

                        <id>timestamp-property</id>

                        <phase>validate</phase>

                        <goals>
                            <goal>timestamp-property</goal>
                        </goals>

                        <configuration>

                            <name>current.timestamp</name>

                            <pattern>
                                yyyy-MM-dd_hh-mm-ss-a
                            </pattern>

                            <timeZone>
                                Asia/Kolkata
                            </timeZone>

                        </configuration>

                    </execution>

                </executions>

            </plugin>

            <!-- Maven Compiler Plugin -->
            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>

                <configuration>

                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>

                </configuration>

            </plugin>

            <!-- Maven Surefire Plugin -->
            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>

                <configuration>

                    <!-- Runner Class -->
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>

                    <!-- Allure Results -->
                    <systemPropertyVariables>

                        <allure.results.directory>
                            ${project.basedir}/HTMLREPORT/allure-results
                        </allure.results.directory>

                    </systemPropertyVariables>

                </configuration>

            </plugin>

            <!-- Allure Maven Plugin -->
            <plugin>

                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>${allure.plugin.version}</version>

                <configuration>

                    <!-- Allure Results -->
                    <resultsDirectory>
                        ${project.basedir}/HTMLREPORT/allure-results
                    </resultsDirectory>

                    <!-- Date & Time Wise Reports -->
                    <reportDirectory>
                        ${project.basedir}/HTMLREPORT/allure-report-${current.timestamp}
                    </reportDirectory>

                </configuration>

            </plugin>

            <!-- Auto Generate Allure Report -->
            <plugin>

                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>

                <executions>

                    <execution>

                        <id>generate-allure-report</id>

                        <phase>test</phase>

                        <goals>
                            <goal>exec</goal>
                        </goals>

                        <configuration>

                            <!-- Allure Executable -->
                            <executable>
                                C:\Users\Kumar\scoop\shims\allure.cmd
                            </executable>

                            <arguments>

                                <argument>generate</argument>

                                <argument>
                                    ${project.basedir}/HTMLREPORT/allure-results
                                </argument>

                                <argument>-o</argument>

                                <argument>
                                    ${project.basedir}/HTMLREPORT/allure-report-${current.timestamp}
                                </argument>

                                <argument>--clean</argument>

                            </arguments>

                        </configuration>

                    </execution>

                </executions>

            </plugin>

        </plugins>

    </build>

</project>